### ISSUE TITLE
ToDo: Lightning Docs

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/developer-docs#444]
- [ ] lightning::channels::close_channel

Request
```
{
  "userpass": "testpsw",
  "mmrpc": "2.0",
  "method": "lightning::channels::close_channel",
  "params": {
    "coin": "tBTC-TEST-lightning",
    "rpc_channel_id": 1,
    "force_close": false
    },
  "id": 0
 }
```

Response
```
{
  "mmrpc": "2.0",
  "result": "Initiated closing of channel with rpc_channel_id: 4",
  "id": 0
}
```
- [ ] lightning::channels::get_channel_details

Request
```
{
  "userpass": "testpsw",
  "mmrpc": "2.0",
  "method": "lightning::channels::get_channel_details",
  "params": {
    "coin": "tBTC-TEST-lightning",
    "rpc_channel_id": 1
  },
 "id": 0
}
```

Response
```
{
  "mmrpc": "2.0",
  "result": {
    "status": "Closed",
    "details": {
      "rpc_id": 1,
      "channel_id": "990a318b486c47e4997441407a1d1266b3468b0e5132d3a7e466e7863ebe2e3a",
      "counterparty_node_id": "038863cf8ab91046230f561cd5b386cbff8309fa02e3f0c3ed161a3aeb64a643b9",
      "closure_reason": "Channel closed because of an exception: We consider the minimum depth to be unreasonably large. Expected minimum: (1). Actual: (3)",
      "is_outbound": true,
      "is_public": false,
      "is_closed": true,
      "created_at": 1677839640,
      "closed_at": 1677839640
    }
  },
  "id": 0
}
```
- [ ] lightning::channels::get_claimable_balances

Request
```
{
    "userpass": "testpsw",
    "mmrpc": "2.0",
    "method": "lightning::channels::get_claimable_balances",
    "params": {
        "coin": "tBTC-TEST-lightning",
        "include_open_channels_balances": false
    },
    "id": 762
}
```

Response
```

  "mmrpc": "2.0",
  "result": [
    {
      "ClaimableOnChannelClose": {
        "claimable_amount_satoshis": 409817
      }
    }
  ],
  "id": 762
}
```
- [ ] lightning::channels::list_closed_channels_by_filter

Request
```
{
    "userpass": "testpsw",
    "mmrpc": "2.0",
    "method": "lightning::channels::list_closed_channels_by_filter",
    "params": {
        "coin": "tBTC-TEST-lightning"
    },
    "id": 55
}
```

Response
```
{
  "mmrpc": "2.0",
  "result": {
    "closed_channels": [
      {
        "rpc_id": 3,
        "channel_id": "24484f88f8bbd96f5a9c732261f515c88d9502684ce1d2151957e56c62f20838",
        "counterparty_node_id": "038863cf8ab91046230f561cd5b386cbff8309fa02e3f0c3ed161a3aeb64a643b9",
        "closure_reason": "Channel closed because of an exception: We consider the minimum depth to be unreasonably large. Expected minimum: (1). Actual: (3)",
        "is_outbound": true,
        "is_public": false,
        "is_closed": true,
        "created_at": 1677840155,
        "closed_at": 1677840155
      },
      {
        "rpc_id": 2,
        "channel_id": "279d718db3e7f6275722b11d9ea3d158637b88605d406a219c4c2289e2f98b6f",
        "counterparty_node_id": "038863cf8ab91046230f561cd5b386cbff8309fa02e3f0c3ed161a3aeb64a643b9",
        "closure_reason": "Channel closed because of an exception: We consider the minimum depth to be unreasonably large. Expected minimum: (1). Actual: (3)",
        "is_outbound": true,
        "is_public": false,
        "is_closed": true,
        "created_at": 1677839733,
        "closed_at": 1677839733
      },
      {
        "rpc_id": 1,
        "channel_id": "990a318b486c47e4997441407a1d1266b3468b0e5132d3a7e466e7863ebe2e3a",
        "counterparty_node_id": "038863cf8ab91046230f561cd5b386cbff8309fa02e3f0c3ed161a3aeb64a643b9",
        "closure_reason": "Channel closed because of an exception: We consider the minimum depth to be unreasonably large. Expected minimum: (1). Actual: (3)",
        "is_outbound": true,
        "is_public": false,
        "is_closed": true,
        "created_at": 1677839640,
        "closed_at": 1677839640
      }
    ],
    "limit": 10,
    "skipped": 0,
    "total": 3,
    "total_pages": 1,
    "paging_options": {
      "PageNumber": 1
    }
  },
  "id": 55
}
```
- [ ] lightning::channels::open_channel

Request
```
{
  "userpass": "testpsw",
  "mmrpc": "2.0",
  "method": "lightning::channels::open_channel",
  "params": {
  "coin": "tBTC-TEST-lightning",
  "node_address": "038863cf8ab91046230f561cd5b386cbff8309fa02e3f0c3ed161a3aeb64a643b9@203.132.94.196:9735",
  "amount": {
  "type": "Exact",
  "value": 0.0004
    }
  },
  "id": 0
 }
```

Response
```
{
  "mmrpc": "2.0",
  "result": {
    "rpc_channel_id": 1,
    "node_address": "038863cf8ab91046230f561cd5b386cbff8309fa02e3f0c3ed161a3aeb64a643b9@203.132.94.196:9735"
  },
  "id": 0
}
```
- [ ] lightning::channels::list_open_channels_by_filter

Request
```
{
    "userpass": "testpsw",
    "mmrpc": "2.0",
    "method": "lightning::channels::list_open_channels_by_filter",
    "params": {
        "coin": "tBTC-TEST-lightning"
    },
    "id": 45
}
```

Response
```
{
  "mmrpc": "2.0",
  "result": {
    "open_channels": [
      {
        "rpc_channel_id": 4,
        "channel_id": "be995ac0fd077960e0aa7e85821d5fd94c1751a2de80f1417274ba4f8fdd890b",
        "counterparty_node_id": "038863cf8ab91046230f561cd5b386cbff8309fa02e3f0c3ed161a3aeb64a643b9",
        "funding_tx": "0b89dd8f4fba747241f180dea251174cd95f1d82857eaae0607907fdc05a99be",
        "funding_tx_output_index": 0,
        "funding_tx_value_sats": 410000,
        "is_outbound": true,
        "balance_msat": 410000000,
        "outbound_capacity_msat": 405900000,
        "inbound_capacity_msat": 0,
        "is_ready": false,
        "is_usable": false,
        "is_public": false
      }
    ],
    "limit": 10,
    "skipped": 0,
    "total": 1,
    "total_pages": 1,
    "paging_options": {
      "PageNumber": 1
    }
  },
  "id": 45
}
```
- [ ] lightning::nodes::add_trusted_node

Request
```
{
  "userpass": "testpsw",
  "mmrpc": "2.0",
  "method": "lightning::nodes::add_trusted_node",
  "params": {
    "coin": "tBTC-TEST-lightning",
    "node_id": "038863cf8ab91046230f561cd5b386cbff8309fa02e3f0c3ed161a3aeb64a643b9"
  },
  "id": 0
}
```

Response
```
{
  "mmrpc": "2.0",
  "result": {
    "added_node": "038863cf8ab91046230f561cd5b386cbff8309fa02e3f0c3ed161a3aeb64a643b9"
  },
  "id": 0
}
```
- [ ] lightning::nodes::connect_to_node

Request
```
{
  "userpass": "testpsw",
  "mmrpc": "2.0",
  "method": "lightning::nodes::connect_to_node",
  "params": {
    "coin": "tBTC-TEST-lightning",
    "node_address": "038863cf8ab91046230f561cd5b386cbff8309fa02e3f0c3ed161a3aeb64a643b9@203.132.94.196:9735"
    },
  "id": 0
 }
```

Response
```
{
  "mmrpc": "2.0",
  "result": "Connected successfully to node : 038863cf8ab91046230f561cd5b386cbff8309fa02e3f0c3ed161a3aeb64a643b9@203.132.94.196:9735",
  "id": 0
}
```
- [ ] lightning::nodes::list_trusted_nodes

Request
```
{ 
 "userpass": "tstpsw", 
 "mmrpc": "2.0", 
 "method": "lightning::nodes::list_trusted_nodes", 
 "params": { 
   "coin": "tBTC-TEST-lightning" 
   }, 
 "id": 0
 }
```

Response
```
 {
  "mmrpc": "2.0",
  "result": {
    "trusted_nodes": [
      "038863cf8ab91046230f561cd5b386cbff8309fa02e3f0c3ed161a3aeb64a643b9"
    ]
  },
  "id": 0
}
```
- [ ] lightning::nodes::remove_trusted_node

Request
```
{
  "userpass": "testpsw",
  "mmrpc": "2.0",
  "method": "lightning::nodes::remove_trusted_node",
  "params": {
    "coin": "tBTC-TEST-lightning",
    "node_id": "038863cf8ab91046230f561cd5b386cbff8309fa02e3f0c3ed161a3aeb64a643b9"
  },
  "id": 0
 }
```

Response
```
{
  "mmrpc": "2.0",
  "result": {
    "removed_node": "038863cf8ab91046230f561cd5b386cbff8309fa02e3f0c3ed161a3aeb64a643b9"
  },
  "id": 0
}
```
- [ ] lightning::payments::generate_invoice

Request
```
{
   "userpass": "testpsw",
   "mmrpc": "2.0",
   "method": "lightning::payments::generate_invoice",
   "params": {
       "coin": "tBTC-TEST-lightning",
       "description": "test invoice",
       "amount_in_msat": 10000
   },
   "id": 22
}
```

Response
```
{
  "mmrpc": "2.0",
  "result": {
    "payment_hash": "1b4a4c52ddcceb248f1c982c6c152b3c0296ef16f93d75d6db71cd54b93f8292",
    "invoice": "lntb100n1pjqrk76dq5w3jhxapqd9h8vmmfvdjsnp4qdpsmhvk75k6e8hhts096j83d45fp56fpzwuyveftaxp6tv9ynxt6pp5rd9yc5kaen4jfrcunqkxc9ft8spfdmckly7ht4kmw8x4fwfls2fqsp5ta3qqr4vjqstgj05h54wj2uf4e49mp6cnxjtmxmvnflffg2ma2ws9qyysgqcqpcxqrrssch3wneqyq70mgc20xu2n40q07a3g8qsuqhgfjyaqunglxu6g9qmkyx3a7qpzppw0s80hj8jvqfpymumn0kavzq3tszycjxppzggf72qq2rzq6g"
  },
  "id": 22
}
```
- [ ] lightning::payments::send_payment

Request
```
{
    "userpass": "testpsw",
    "mmrpc": "2.0",
    "method": "lightning::payments::send_payment",
    "params": {
        "coin": "tBTC-TEST-lightning",
        "payment": {
            "type": "invoice", 
            "invoice": "lntb10u1pjqrksjpp50flznka8zxmqpc52lm53tt9h7wz96xsfh8pffxft3zpfau062j2qdq5xysyymr0ddskxcmfdehsxqrrsscqp79qy9qsqsp5vrasm508q6w4jv6agmgcw7p3uu2k0g8g8egefnd2gycvk922z4nsxl6sw4a5y26ntw8zt4sejzvyknmrd8lvj586uaj2h8ee6qq9zqf3js6flaappwz0634h29xdr5805w33u6g75pfph7l27fjmnsushrsqld7zfm"
        }
    },
    "id": 12
}
```
- [ ] task::enable_lightning::cancel

Request
```
{
 "userpass": "testpsw",
 "mmrpc": "2.0",
 "method": "task::enable_lightning::cancel",
 "params": {
   "task_id": 0
   },
   "id":0
 }
```

Response
```
{
  "mmrpc": "2.0",
  "result": "success",
  "id": 0
}
```
- [ ] task::enable_lightning::init

Request
```
{
 "userpass": "testpsw",
 "mmrpc": "2.0",
 "method": "task::enable_lightning::init",
 "params": {
   "ticker": "tBTC-TEST-lightning",
   "activation_params": {
     "name": "Mm2TestNode",
     "listening_port": 9735,
     "color": "000000",
     "payment_retries": 5,
     "backup_path": null  
     }
   },
  "id": 0
 }
```

Response
```
{
  "mmrpc":"2.0",
  "result":{
    "task_id":0
  },
  "id":0
}
```
- [ ] task::enable_lightning::status

Request
```
"{
 ""userpass"": ""testpsw"",
 ""mmrpc"": ""2.0"",
 ""method"": ""task::enable_lightning::status"",
 ""params"": {
   ""task_id"": 0,
   ""forget_if_finished"": true
   },
  ""id"": 0
 }"
```

Response
```
{
  "mmrpc": "2.0",
  "result": "success",
  "id": 0
}
```

- [ ] lightning::payments::get_payment_details

Request
```
{
    "userpass": "testpsw",
    "mmrpc": "2.0",
    "method": "lightning::payments::get_payment_details",
    "params": {
        "coin": "tBTC-TEST-lightning",
        "payment_hash": "32f996e6e0aa88e567318beeadb37b6bc0fddfd3660d4a87726f308ed1ec7b33"
    },
    "id": 1
}
```

Response

- [ ] lightning::payments::list_payments_by_filter

Request
```
{
    "userpass": "testpsw",
    "mmrpc": "2.0",
    "method": "lightning::payments::list_payments_by_filter",
    "params": {
        "coin": "tBTC-TEST-lightning"
         }
    },
     "id": 2
}
```

Response

- [ ] lightning::channels::update_channel
Request
Response
